variables:
  MOD_CACHE_DIR: .mod-cache
stages:
  - build
  - test

build:
  stage: build
  image: golang:1.11
  before_script:
    - mkdir -p $GOPATH/pkg/mod
    - "[ -d $MOD_CACHE_DIR ] && cp -r $MOD_CACHE_DIR/. $GOPATH/pkg/mod"
  script:
    - go build ./...
    - cp -r $GOPATH/pkg/mod/. $MOD_CACHE_DIR
  cache:
    key: $CI_PROJECT_ID
    paths:
      - $MOD_CACHE_DIR
  only:
    - branches

.test:
  stage: test
  image: docker:stable
  services:
    - docker:stable-dind
  cache:
    key: $CI_PROJECT_ID
    paths:
      - $MOD_CACHE_DIR
    policy: pull
  before_script:
    - apk add -q py-pip
    - pip install -q docker-compose
    - cp ./.ci/docker-compose.override.yml .
  script:
    - docker-compose pull -q
    - docker-compose up -d
    - docker-compose run watermill ./.ci/wait-for-services.sh
    - "echo Running tests with flags: $TEST_FLAGS"
    - docker-compose run watermill go test ./... $TEST_FLAGS

test_short:
  extends: .test
  variables:
    TEST_FLAGS: "-short"
  only:
    - branches

test_full:
  extends: .test
  only:
    - master

test_race:
  extends: .test
  variables:
    TEST_FLAGS: "-short -race"
  only:
    - master
